apiVersion: v1 
kind: Secret 
metadata: 
  name: tempo-s3-secret 
  namespace: tracing-system 
stringData: 
  endpoint: http://s3.openshift-storage.svc 
  bucket: <S3 bucket name>
  access_key_id: <decoded access key value> 
  access_key_secret: <decoded secret key value> 
type: Opaque
