apiVersion: objectbucket.io/v1alpha1 
kind: ObjectBucketClaim 
metadata: 
  name: tempo-s3 
  namespace: tracing-system 
spec: 
  generateBucketName: tempo-s3 
  storageClassName: openshift-storage.noobaa.io
