apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
spec:
  serviceAccount:
    name: logging-collector
  outputs:
  - name: lokistack-out
    type: lokiStack
    lokiStack:
      target:
        name: logging-loki
        namespace: openshift-logging
      authentication:
        token:
          from: serviceAccount
    tls:
      ca:
        key: service-ca.crt
        configMapName: openshift-service-ca.crt
  pipelines:
  - name: audit-infra-app-logs
    inputRefs:
    - audit
    - application
    - infrastructure
    outputRefs:
    - lokistack-out
  collector:
    tolerations:
    - effect: NoExecute
      key: node-role.kubernetes.io/infra
