apiVersion: quota.openshift.io/v1
kind: ClusterResourceQuota
metadata:
  name: chapter-7-cluster-quota-sts
spec:
  quota:
    hard:
      count/statefulsets.apps: 1
  selector:
    labels:
      matchLabels:
        no-sts: "true"
