apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-block-pvc
spec:
  volumeName: local-block-pv
  accessModes:
    - ReadWriteOncePod
  volumeMode: Block
  resources:
    requests:
      storage: 100Mi
