apiVersion: v1
kind: ResourceQuota
metadata:
  name: chapter-7-quota
  namespace: chapter-7-quota-1
spec:
  hard:
    configmaps: "10" 
    persistentvolumeclaims: "4" 
    replicationcontrollers: "20" 
    secrets: "10" 
    services: "10" 
    pods: "2"
