apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sc-hostpath-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
  storageClassName: crc-csi-hostpath-provisioner
