allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: false
allowPrivilegedContainer: false
allowedCapabilities: null
apiVersion: security.openshift.io/v1
defaultAddCapabilities: null
fsGroup:
  type: MustRunAs
groups: []
kind: SecurityContextConstraints
metadata: 
  annotations: 
    kubernetes.io/description: Chapter 7 Test SCC 
  name: chapter-7-scc 
priority: null 
readOnlyRootFilesystem: false 
requiredDropCapabilities: 
- NET_BIND_SERVICE
runAsUser: 
  type: RunAsAny 
seLinuxContext: 
  type: MustRunAs
seccompProfiles:
- runtime/default
supplementalGroups:
  type: RunAsAny
users: []
volumes:
- configMap
- csi
- downwardAPI
- emptyDir
- ephemeral
- persistentVolumeClaim
- projected
- secret
